---
name: CI
on: workflow_dispatch
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          date
build_on_windows:
  runs-on: windows-latest
  steps:
    - name: run multi-line script run:| echo "hello github actions" Get-Date
